controller_list:
  - name: serial3v3_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_to_e1_joint
      - e1_to_e2_joint
      - e2_to_e3_joint